[project]
name = "fcc-bd-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas",
 "numpy",
 "polars>=1.29.0",
]

[dependency-groups]
dev = ["ipykernel>=6.29.5"]
